### ISSUE TITLE
Automating the update process

### ISSUE THREAD

**Issue by wadhah101** [yassineyahyaoui/top-tunisian-github-users#1]
I am interested in adding an automated GitHub action for updating this list.

Can you share the scraping code used in this project ?

**Comment by yassineyahyaoui** [comment]
Sure, I am working on it to.
Text me on my facebook profile: https://www.facebook.com/yahyaouimohamedyassine/

**Comment by yassineyahyaoui** [comment]
I am adding the code on github.
